services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: clinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/ddl.sql:/docker-entrypoint-initdb.d/01-ddl.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

volumes:
  pgdata:
