apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: clinic
type: Opaque
stringData:
  DATABASE_URL: 'PLACEHOLDER_DATABASE_URL'
  GOOGLE_CLIENT_ID: 'PLACEHOLDER_GOOGLE_CLIENT_ID'
  GOOGLE_CLIENT_SECRET: 'PLACEHOLDER_GOOGLE_CLIENT_SECRET'
  GOOGLE_CALLBACK_URL: 'PLACEHOLDER_GOOGLE_CALLBACK_URL'
  JWT_SECRET: 'PLACEHOLDER_JWT_SECRET'
  JWT_EXPIRES_IN: '15m'
  FRONTEND_URL: 'PLACEHOLDER_FRONTEND_URL'
